version: 2 

sources: 
  - name: semantics
    database: sm_db
    schema: sm_schema
    tables:
      - name: patient_raw
      - name: appt_raw
      - name: doctor_raw
      - name: corp_time_table
      - name: clinic_raw
      
      